[package]
name = "mc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
overflow-checks = false
lto = "fat"
panic = "abort"
codegen-units = 1

[dependencies]
fastrand = "2.1.0"
